---
title: "tidycensus&leaflet"
author: "Emily Ferry"
date: "2/17/2020"
output: html_document
---

```{r setup, include=FALSE}

`%notin%`<-Negate(`%in%`)
req.packages<-c("leaflet","tidycensus","tidyverse","ggthemes","ggExtra","scales")

if(any(installed.packages() %notin% req.packages)){
  missing.packages.inds <- which ( req.packages %notin% installed.packages())
  install.packages(req.packages[missing.packages.inds])
}

eval(
  parse(
    text= paste0('library(',req.packages,')')
  )
)


install.packages("tidycensus")

library(tidycensus)
install.packages("rlang")
library(rlang)

install.


```

860aed0a28eb55d60e92ab2eb82f9cf626b53219


```{r cars}

if(!file.exists("~/.Rprofile"))
  file.create("~/.Rprofile")
file.edit("~/.Rprofile")

#source('~.Rprofile')

Sys.getenv()

census_api_key(key = "860aed0a28eb55d60e92ab2eb82f9cf626b53219",install = TRUE, overwrite = TRUE)

census_api_key(key = census.api.key, install = TRUE)

readRenviron("~/.Renviron")


```

US Census Survey Data 

```{r}
census.2000<-load_variables(year = 2000, "sf1", cache= TRUE)

DT::datatable(
  head(
    census.2000, n = 20
  )
) #this is nice, he would recommend that we use this 



```


Ammerican community Survey 
```{r}

acs.2017 <- load_variables(year = 2017, dataset= 'acs1', cache = TRUE)

DT::datatable( 
  head(
    acs.2017, n=20
    )
  )

Mrktg_sales_mincome<-get_acs(geography = "county",
       state = "NY",
       variables= c(medianincomeMrktgSales="B19013_001"),
       keep_geo_vars= TRUE, 
       cache_table= TRUE,
      geometry = TRUE)


Mrktg_sales_mincome %>%
  top_n(20,estimate) %>%
  rename(county= GEOID)%>%
  mutate(county = as.factor(county))
  
  
  ggplot(data=Mrktg_sales_mincome, aes(y = reorder(GEOID,estimate), x=estimate))+
  geom_point()+
  theme_tufte()+
  theme(axis.title = element_blank())+
  scale_x_continuous(labels = scales::dollar)+
  ggtitle(label = "NY Median Household Income for Marketing and Sales Managers")





```
Working with ACS/CENSUS data 

use the workhorse functions described above

ACS survey has more data so well use it for demonstration - the get_acs has many arguments 

leaflet 

```{r}

sjfc<-leaflet() %>%
  addTiles() %>%#add default opensstreetmap titles 
  addMarkers(lng= -77.509, lat= 43.1157,popup = "SJFC::GDAT515")


sjfc # printing our maps here sd


```



```{r}

color.pal <-colorNumeric(palette ="viridis", domain = Mrktg_sales_mincome$estimate)


```


```{r}
income.map <- leaflet(data = Mrktg_sales_mincome)%>%
  addTiles()%>%
  setView(lng = -77.509, lat= 43.1157,zoom = 8) %>%
  addPolygons(fillColor = ~color.pal(Mrktg_sales_mincome$estimate), #addpolygons is the geometry
             fillOpacity = 0.9,
             fill= TRUE, 
             weight =0.7,
             smoothFactor = 0.3,
             color = "black",
             #highlight = highlightOptions(weight = 2,
                                        #  color = "Black",
                                         # FillOpacity = 0.9, 
                                          #bringToFront = FALSE),
         popup = ~paste("<b>Zip Code: </b>", GEOID, "<br>",
               "<b>Median Household Income: </b>", dollar(estimate))
)%>%
  addLegend(position = "topleft", 
            pal = color.pal, 
            values= ~Mrktg_sales_mincome$estimate, 
            title = "Median Income")



income.map

income.map %>%
  addAwesomeMarkers(lng = -77.509, lat = 43.1157, icon = awesomeIcons("fa-university",library = 'fa', markerColor = "red"))
  





```












